# 1 - design
Scenario: 1.1 Should find a guitar by its serial number
  Given: An inventory of guitars
  When: We search for serialnumber
  Then: We get a guitar or null

Scenario: 1.2 Should search for guitars based on criteria
  Given: An inventory of guitars
  When: We search for a multiple criteria
  Then: We get a list of guitarrs matching criteria

Scenario: 1.3 Should search for guitars based on optional criteria
  Given: An inventory of guitars
  When: We search for a criteria
  Then: We get a list of guitars matching criteria

Scenario: 1.4 Should search for guitars avoiding user mistakes
  Given: An inventory of guitars
  When: We search for criteria
  Then: We get a list of guitars matching criteria

Scenario: 1.5 Should have numberOfStrings in specs
  Given: An inventory of guitars
  When: We have 6-string or 12-string guitars
  Then: We can add them

Scenario: 1.5 Should search for number of strings
  Given: An inventory of guitars
  When: We search for 6-string or 12-string guitars
  Then: We get a list of guitars matching criteria
---
# change
Scenario: 2.1 Should support for mandolins
  Given: An inventory of guitars
  When: We can add mandolines
  Then: We guitars and mandollines

Scenario: 2.2 Should search for mandolins
  Given: An inventory of guitars and mandolins
  When: We search for mandolins
  Then: We get a list of mandolins